import * as vscode from 'vscode';

const WORKSPACE_DIR = '.wix-data-view';

/**
 * The injected globals available inside a query, declared as ambient types so
 * VSCode's TypeScript service offers type-aware auto-complete for them.
 *
 * This MUST stay in sync with the module bindings in `queryRunnerWorker.ts`.
 * Imports are aliased (`...Ns`) to avoid colliding with the global names being
 * declared, which would otherwise make the `typeof` references self-referential.
 */
const GLOBALS_DTS = `// Generated by the Wix Data View extension. Do not edit.
import type * as wixDataItemsSdk from '@wix/wix-data-items-sdk';
import type {
  collections as collectionsNs,
  indexes as indexesNs,
  backups as backupsNs,
  movementJobs as movementJobsNs,
  externalDatabaseConnections as externalDatabaseConnectionsNs,
} from '@wix/data';

declare global {
  const wixData: typeof wixDataItemsSdk;
  const collections: typeof collectionsNs;
  const indexes: typeof indexesNs;
  const backups: typeof backupsNs;
  const movementJobs: typeof movementJobsNs;
  const externalDatabaseConnections: typeof externalDatabaseConnectionsNs;
}

export {};
`;

// `*` ignores the whole managed folder (including this file and the generated
// project files) so the ephemeral query workspace never lands in the user's repo.
const GITIGNORE = '*\n';

/** Reads the setting that toggles the on-disk (auto-complete) query mode. */
export function isAutocompleteEnabled(): boolean {
  return vscode.workspace
    .getConfiguration('vscode-wix-data-view.queryEditor')
    .get<boolean>('enableAutocomplete', true);
}

/**
 * Location of the managed query folder, inside the first open workspace folder.
 * Auto-complete requires the query file to live in a folder VSCode already
 * treats as a real project root; a programmatically-added folder (e.g. one in
 * global storage) stays in "Partial mode" and never picks up the project. So we
 * place the files under an existing workspace root instead. Returns `undefined`
 * when no folder is open — the caller then falls back to the legacy untitled mode.
 */
function workspaceDir(): vscode.Uri | undefined {
  const root = vscode.workspace.workspaceFolders?.[0]?.uri;
  return root ? vscode.Uri.joinPath(root, WORKSPACE_DIR) : undefined;
}

function buildJsConfig(context: vscode.ExtensionContext): string {
  // Map `@wix/*` imports to the extension's bundled node_modules so the real
  // SDK types resolve without copying anything. Forward slashes work on all
  // platforms in tsconfig paths.
  const wixModules = vscode.Uri.joinPath(context.extensionUri, 'node_modules', '@wix').fsPath
    .split(/[\\/]/)
    .join('/');

  const config = {
    compilerOptions: {
      allowJs: true,
      checkJs: false, // completions only, no type-error squiggles
      module: 'commonjs',
      moduleResolution: 'node',
      target: 'es2020',
      baseUrl: '.',
      paths: { '@wix/*': [`${wixModules}/*`] },
      types: [] as string[],
    },
    include: ['**/*.wdq.js', 'globals.d.ts'],
  };

  return JSON.stringify(config, null, 2);
}

async function writeFile(uri: vscode.Uri, content: string): Promise<void> {
  await vscode.workspace.fs.writeFile(uri, Buffer.from(content, 'utf8'));
}

/**
 * Ensures the managed query folder and its TS project files exist inside the
 * open workspace. Idempotent and safe to call before opening each query — it
 * does NOT delete query files. Returns the folder where query files should be
 * written, or `undefined` when no workspace folder is open.
 */
export async function ensureQueryWorkspace(context: vscode.ExtensionContext): Promise<vscode.Uri | undefined> {
  const dir = workspaceDir();
  if (!dir) {
    return undefined;
  }

  await vscode.workspace.fs.createDirectory(dir);
  await writeFile(vscode.Uri.joinPath(dir, '.gitignore'), GITIGNORE);
  await writeFile(vscode.Uri.joinPath(dir, 'jsconfig.json'), buildJsConfig(context));
  await writeFile(vscode.Uri.joinPath(dir, 'globals.d.ts'), GLOBALS_DTS);
  return dir;
}

/**
 * Removes leftover query files from previous sessions, giving each session a
 * clean slate. Best-effort: missing folder or undeletable files are ignored.
 */
export async function cleanupQueryFiles(): Promise<void> {
  const dir = workspaceDir();
  if (!dir) {
    return;
  }

  let entries: [string, vscode.FileType][];
  try {
    entries = await vscode.workspace.fs.readDirectory(dir);
  } catch {
    return; // folder doesn't exist yet
  }

  await Promise.all(
    entries
      .filter(([name]) => name.endsWith('.wdq.js'))
      .map(([name]) =>
        vscode.workspace.fs
          .delete(vscode.Uri.joinPath(dir, name))
          .then(undefined, () => undefined)
      )
  );
}
